name: Linting

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: check --config=./pyproject.toml
